#98, #98 - 로그인, 로그아웃(내 계정) 페이지 구현
woowa-techcamp-2021/deal-16 pull request #114
Opened 2021-07-19 12:53 UTC by juyoungpark718

- 로그인 후 받은 토큰을 localstorage에 저장
- form tag의 경우 enter 입력시 submit이 자동으로 발생하는 문제 -> div 태그로 수정
- main 컴포넌트에서 userinfo 클릭 시 token에 유무에 따라 login, logout 페이지로 갈 수 있게 수정
- logoutHandler는 localstorage를 비우고 main으로 routing
- getUser는 token이 없는 경우, 토큰이 검증이 실패한 경우 main으로 routing
   - token이 없는 경우에 router.to에 setTimeout을 걸어줬는데, router.to로 logout으로 오고 logout 함수를 실행하는 과정에서 router.to를 그냥하게되면, logout함수가 끝나고 logout을 부른 router가 나머지 진행이 되서 logout페이지가 그냥 다시뜨는 오류가 있음. 그래서 settimeout을 사용함

- page가 붙어있지 않은 함수들 page 붙여서 수정

### 추가해야할 사항

- 내 계정 페이지에서는 사용자 정보를 불러와서 보여줘야하기 때문에 백엔드 개발 후 연결해야함.
- router.to 같은 경우는 history를 남기고, router.render는 history를 남기지 않지만 url path를 바꾸지 않음. 근데 로그아웃 같은 경우에는 history에 저장할 필요가 없기 때문에 history를 한칸 비워주는 함수를 추가해야할 것 같음(render로 해결하려 했지만, path가 남아서 실패).

2021-07-19 13:28 UTC, hwookim requested changes
몇가지 리뷰 남겼으니 확인 부탁드립니다.

겸사겸사,,
로그아웃 화면은 조금 다른 것 같습니다!
<img width="204" alt="스크린샷 2021-07-19 오후 10 20 22" src="https://user-images.githubusercontent.com/45786387/126166233-2aa62b58-87e3-4bf7-aabe-40aab0b0e54f.png">

2021-07-19 13:28 UTC, hwookim commented on frontend/src/pages/login/index.ts
> +function logInHandler($idInput: HTMLInputElement): (event: MouseEvent) => void {
```suggestion
function loginHandler($idInput: HTMLInputElement): (event: MouseEvent) => void {
```
자잘한 오타입니다 ㅎㅎ

2021-07-19 13:28 UTC, hwookim commented on frontend/src/pages/login/index.ts
> +    logInHandler($idInput as HTMLInputElement)
함수를 바깥으로 빼니 이런 문제가 발생하는군요...
일단 이렇게 진행하고 추후 리팩토링을 논의해봐야겠네요 😢

2021-07-19 13:28 UTC, hwookim commented on frontend/src/pages/logout/index.ts
> +  //   });
이 부분은 이렇게 작성하신 이유가 있을까요?

그냥 token이 없는 경우 alert후 바로 router.to("/login")으로 해도 되지 않을까 싶습니다.
setTimeoust도 필요한지 잘 모르겠어요.

2021-07-19 13:28 UTC, hwookim commented on frontend/src/pages/main/index.ts
> +  }
페이지가 새로 로딩되지 않고 중간에 토큰이 사라지더라도 logout 페이지로 가겠네요.
별도 함수를 통해 ueserBtn click시 라우팅할 대상을 변경하는 건 어떨까요?

2021-07-19 16:12 UTC, juyoungpark718 commented on frontend/src/pages/main/index.ts
> +  }
앗 그러네요. 중간에 사라지는 경우를 생각을 못했습니다. 고쳐보도록 하겠습니다!

2021-07-19 16:13 UTC, juyoungpark718 commented on frontend/src/pages/logout/index.ts
> +  //   });
PR메세지에 작성해놓은대로, router.to("/login") 혹은 router.to("/") 등 router.to를 하게 되면 정상적으로 작동하지 않습니다.. ㅠㅠ
해당 부분에 대해서는 나중에 한번 같이 보면 좋을까요?

2021-07-19 16:14 UTC, juyoungpark718 commented on frontend/src/pages/login/index.ts
> +    logInHandler($idInput as HTMLInputElement)
함수가 바깥에 있어서 접근할 방도가 없어서.. 이런식으로 처리를 했습니다. 후에 리펙토링하면 좋을 것 같아요 !

2021-07-19 16:14 UTC, juyoungpark718 commented on frontend/src/pages/login/index.ts
> +function logInHandler($idInput: HTMLInputElement): (event: MouseEvent) => void {
수정하겠습니다!

2021-07-20 00:52 UTC, hwookim commented on frontend/src/pages/logout/index.ts
> +  //   });
라우터에 전반적인 구조 문제가 있군요...ㅠ

2021-07-20 00:53 UTC, hwookim approved these changes
라우터에 대한 문제점이 드러나서,
별도 PR에서 작업하는 쪽으로 합시다! ㅠㅠ

나머지는 다 좋네요 ㅎㅎ

2021-07-20 00:57 UTC, merged