#22 - 드롭다운 구현
woowa-techcamp-2021/deal-16 pull request #115
Opened 2021-07-19 16:30 UTC by juyoungpark718

### Dropdown 컴포넌트

```typescript
export interface IDropdownItem {
  text: string;
  danger?: boolean;
  className?: string;
  id?: string;
  onClick?: (event: any) => void;
}

export interface IDropdownProps {
  style: {
    [key: string]: string;
  };
  items: IDropdownItem[];
  delegate?: (event: any) => void;
  parentSelector: string;
}
```

### 가이드

1. Dropbox가 들어갈 대상은 `position: relative` 이여야함

2. dropdown의 style 지정

   ```js
   // absolute이기 때문에, dropdown 위치를 조정하기 위해서 top, left, right 등을 설정해줘야함.
   const dropdownStyle = {
       top: "90%",
       left: "0",
     };
   
   ```

3. (선택)dropdownItem을 설정

   ```typescript
   const dropdownItems: IDropdownItem[] = [
       { text: "수정하기" },
       { text: "삭제하기", danger: true },
     ];
   
   /*
   * dropdownitem에 각각 onClick 이벤트를 걸 수 있음.
   * className, id를 적용해서 dropdown 컴포넌트에 delegate를 하는 경우 사용 가능
   * danger를 표시해서 글자 색을 빨간색으로 수정 가능
   */
   ```

4. (선택) dropdown delegate 이벤트 적용
   1. dropdown에 걸 이벤트를 지정하고, 해당 이벤트에서 dropdownItem들의 클래스나, 아이디로 해당 item을 찾고 각 이벤트 발생 시 동작을 수행할 수 있음.

5. parentSelector

   1. Dropdown 옵션으로 parentSelector 꼭 추가해야 함

   2. ```typescript
      function removeDropdown($dropdown: HTMLElement, parentSelector: string) {
        return function removeHandler(event: MouseEvent) {
          const target = event.target as HTMLElement;
      
          if (target.closest(parentSelector)) return;
          $dropdown.parentElement?.removeChild($dropdown);
          document.body.removeEventListener("click", removeHandler);
        };
      }
      ```

   3. dropdown을 감싸고 있는 부모 외의 곳을 클릭하면 꺼지게 이벤트를 달아놨음

6. dropdown을 띄우게 하는 eventListener

   ```typescript
   $locationBtn.addEventListener("click", () => {
       try {
         findElement($locationBtn, ".dropdown");
       } catch (err) {
         $locationBtn.appendChild(
           Dropdown({
             style: dropdownStyle,
             items: dropdownItems,
             parentSelector: ".main-header__center",
           })
         );
       }
     });
   ```

   Dropdown이 없는 경우만 추가해야하므로 해당과 같이 작성해야한다.

- 리펙토링 혹은 오류가 있을 수 있는데, 사용하면서 찾아야할 것 같습니다.(main에 적용해보긴 했는데 작동했습니다)
- 리뷰로 찾아주신다면 바로 수정하도록 하겠습니다!

close #22

2021-07-19 17:55 UTC, hwookim requested changes
진짜 고생하셨습니다...ㄷㄷ
몇가지 리뷰 남겻으니 확인 부탁드려요!
그 외에 또 남길 부분도 아래에 남기겠습니다.

메인과 PostPage에 적용한 채로 PR을 올려도 좋을 것 같아요.

dropboxItem에 hover 시 cursor:pointer를 추가하면 좋을 것 같습니다!

2021-07-19 17:55 UTC, hwookim commented on frontend/src/components/Dropdown/index.ts
> +  </div>
`items.forEach((item)=>$list.appendChilde(Component(item)))`
여태 이런 식으로만 했었는데,
왜 이 방법을 생각하지 못했을까요!

좋은 방법인 것 같습니다. 👍🏼

2021-07-19 17:55 UTC, hwookim commented on frontend/src/components/Dropdown/index.ts
> +    if (target.closest(parentSelector)) return;
저는 모든 if, else 문에는 중괄호가 들어가야한다고 생각합니다.

우선 전체적으로 코드를 쭉 훑을 때 조건절이 길어지면 한줄이더라도 정확히 if문 안에 든 것이 무엇인지 알기 힘든 경우도 있고,
코드를 수정할 때 실수할 여지가 많아진다고 봅니다.

중괄호를 통해 분리한다면 코드가 조금 더 길어질진 몰라도, 더 깔끔해지고 가독성이 좋아진다고 보는데, 어떻게 생각하시나요?

2021-07-19 17:55 UTC, hwookim commented on frontend/src/components/Dropdown/index.ts
> +  }" ${selector}>${text}</div>`;
어차피 classname을 받아올 거라면,
사용하는 컴포넌트 쪽에서 색상을 정해줘도 괜찮지 않을까요?

Dropdown 자체에 너무 많은 옵션이 있다고도 느껴집니다.

클래스를 넘기기 때문에, onClick 이벤트의 경우에도 부모 컴포넌트에서 작업해도 괜찮지 않을까요?

2021-07-19 17:55 UTC, hwookim commented on frontend/src/components/Dropdown/index.ts
> +  }
```suggestion
  if (danger) {
  return `
    <div 
      ${id ? `id=${id}` : ""}
      class="dropdown__item ${className || ""}" 
    >
      ${text}
    </div>
  `;
  }
```
selector 부분은 이런식으로도 표현 가능할 것 같아요.

2021-07-19 17:55 UTC, hwookim commented on frontend/src/components/Dropdown/index.ts
> +    ${props.items.map((item: IDropdownItem) => makeDropdownItem(item)).join("")}
```suggestion
    ${props.items.map(makeDropdownItem).join("")}
```

이런 식으로 표현도 가능하겠네요.

`makeDropdownItem`을 컴포넌트화 해서 상단으로 올리거나 분리하는 건 어떨까요?

2021-07-20 01:14 UTC, juyoungpark718 commented on frontend/src/components/Dropdown/index.ts
> +  }
삼항연산자로 바꿔보겠습니다 !

2021-07-20 01:15 UTC, juyoungpark718 commented on frontend/src/components/Dropdown/index.ts
> +    ${props.items.map((item: IDropdownItem) => makeDropdownItem(item)).join("")}
상단으로 올려보도록 하겠습니다 !!

2021-07-20 01:30 UTC, juyoungpark718 commented on frontend/src/components/Dropdown/index.ts
> +    if (target.closest(parentSelector)) return;
왼쪽에서 부터 코드를 읽고, 중괄호가 있다면 if문과 return문과 가까이 있어서 보기 편해지는 것은 맞는 것 같습니다. 앞으로 이렇게 적용하도록 하겠습니다.

2021-07-20 12:19 UTC, hwookim requested changes
어려운 점이 자꾸 많군요...ㅠㅠㅠㅠ
몇가지 리뷰 남겼으니 확인 부탁드려요!

---

컴포넌트 구조에 대해,
맨 처음 논의되었던 것들 중 함수 내부에 모든 함수를 정의하고 init을 통해 그 흐름을 나타내는 방법은 어떤가 싶어요.
`filterByLocation`함수처럼 DOM객체를 넘겨주는 일이 발생하네요.
메모리 상 퍼포먼스가 떨어지긴 합니다만, 저희 프로젝트 내에서는 퍼포먼스 저하의 손실보다 코드 가독성 향상의 이익이 더 크지 않나 싶습니다.

2021-07-20 12:19 UTC, hwookim commented on frontend/src/pages/main/index.ts
> +}
함수의 역할이 2개인 건가요?
toggle하는 것과 boolean 값을 반환하는 것은 확연히 다른 역할 같습니다.

filterByLocation 코드만 보면 boolean값을 체크하는 것 같으면서도 동시에 toggle까지 일어나는 모양이 되네요.
hide 여부를 검사하는 것 / toggle 을 분리해 hide일 때 return을 하고 아니면 직접 open을 하는 방식으로 진행하는 편이 낫지 않을까요?

2021-07-20 12:19 UTC, hwookim commented on frontend/src/pages/main/index.ts
> +function filterByLocation(
이벤트 핸들러의 네이밍은 `~Handler`로 하기로 했으니 변경하면 좋을 것 같아요.
위의 toggle도요.

제가 `~Handler` 방식의 네이밍에 익숙치 않아서,
`filterByLocation`과 같은 경우에는 filter에 초점을 맞추는 게 맞나요?
`filterPostHandler`같은 식이 되는 게 맞을까요?🤔

2021-07-20 12:26 UTC, juyoungpark718 commented on frontend/src/pages/main/index.ts
> +}
함수의 역할을 분리했습니다 !! 감사합니다 👍

2021-07-20 15:00 UTC, hwookim approved these changes
몇가지 리뷰만 확인해주세요!
적용 여부는 주영님의 생각에 맡기겠습니다!

2021-07-20 15:02 UTC, juyoungpark718 commented on frontend/src/pages/main/index.ts
> +function existDropdown($dropdown: HTMLElement): boolean {
is로 바꿔 보겠습니다.. ㅎㅎ

2021-07-20 19:22 UTC, hwookim commented on frontend/src/pages/main/index.ts
> +    $postList.appendChild(fragment);
잦은 reflow를 막기 위해! 👍🏼

2021-07-21 01:13 UTC, merged