로그인 페이지 레이아웃 구성
woowa-techcamp-2021/deal-16 pull request #96
Opened 2021-07-18 16:14 UTC by juyoungpark718

- Button, Input 컴포넌트는 후에 회원가입, 내 계정 페이지에서 사용하기위해 component로 분리

### 논의할 사항
- login 페이지 레이아웃에서 form 태그의 위치를 absolute로 중앙 배치 했는데, 이 방법 말고 좋은 방법 있는지 논의하고 싶음

close #40

2021-07-18 16:59 UTC, hwookim requested changes
여러개가 한번에 우수수 올라왔군요.
그래도 레이아웃이 빠르게 끝나가는 것 같아 좋습니다 ㅎㅎ
저도 내일 바로 글쓰기 레이아웃 완성하겠습니다...ㅠㅠ 주말동안 하려고 했는데 제대로 하질 못했네요

몇가지 리뷰 남겼으니 확인 부탁드려요!

나머지 PR들은 자고 일어나서 하도록 하겠습니다!

2021-07-18 16:59 UTC, hwookim commented on frontend/src/components/Button/index.ts
> +    }
```suggestion
    if (selector.startsWith(".")) {
      $button.classList.add(selector);
    } else if (selector.startsWith("#")) {
      $button.id = selector;
    }
```

이게 좀 더 직관적이네요.
다만 이렇게 되면 class에 .이 들어가거나 id가 #으로 시작하진 않나요?

2021-07-18 16:59 UTC, hwookim commented on frontend/src/components/Button/style.scss
> +  }
버튼은 onClick 이벤트가 할당되어있다면 기본적으로 pointer가 적용되지 않나요?

2021-07-18 16:59 UTC, hwookim commented on frontend/src/components/Input/index.ts
> +  $input.setAttribute("placeholder", placeholder);
이걸 보니 template를 위에 빼지 말고 내부에서 props를 모두 받은 채 선언하는 건 어떨까 생각도 드네요

```javascript
function Input(props) {
  const { type = "text", placeholder = "", selector } = props;
  const $input = createElement(`
    <input type="${type}" placeholder="${placeholder}" />
  `);
  ...
}
```

이런 식으로 말예요.
그럼 함수 내부가 너무 더러워지려나요?🤔

2021-07-18 16:59 UTC, hwookim commented on frontend/src/components/Input/style.scss
> +@import "@/common/variables.scss";
```suggestion
@import "~@/common/variables.scss";
```
scss에서 alias는 `~`로 시작해야되더라구요!
실행은 되긴 하는데... 안되는 경우도 있나봅니다 [관련 질문 글](https://stackoverflow.com/questions/34717203/webpack-with-sass-loader-scss-file-import-does-not-recognize-resolve-alias)

그러고보니 alias 설정 할 때 scss들을 적용하지 않았네요..😥

2021-07-18 16:59 UTC, hwookim commented on frontend/src/pages/login/style.scss
> +}
뭐 안될 건 없지 않을까요?
`.login`에 높이를 주고 margin을 주거나 align-items로 설정할 수도 있겠지만,
저는 지금도 간단하고 좋은 것 같습니다! 😀

2021-07-18 16:59 UTC, hwookim commented on frontend/src/pages/main/index.ts
> +      <img class="main-header__right__user-icon"src="${UserIcon}" alt="user" />
```suggestion
      <img class="main-header__right__user-icon" src="${UserIcon}" alt="user" />
```

띄어쓰기..ㅎㅎ

2021-07-19 02:53 UTC, juyoungpark718 commented on frontend/src/components/Button/index.ts
> +    }
오 좋은 것 같습니다. 그리고 id나 class에 .이나 # 들어가는걸 생각을 못했네요 !! 수정하도록 하겠습니다

2021-07-19 02:54 UTC, juyoungpark718 commented on frontend/src/components/Button/style.scss
> +  }
앗 그런가요! cursor가 생기질 않길래 추가했는데, 삭제하도록 하겠습니다!

2021-07-19 02:56 UTC, juyoungpark718 commented on frontend/src/components/Input/style.scss
> +@import "@/common/variables.scss";
흠 저는 아무 문제 없이 작동했는데 고쳐야하는 문제일까요??

2021-07-19 02:57 UTC, juyoungpark718 commented on frontend/src/pages/main/index.ts
> +      <img class="main-header__right__user-icon"src="${UserIcon}" alt="user" />
오마이갓! 감사합니다

2021-07-19 02:59 UTC, juyoungpark718 commented on frontend/src/components/Input/index.ts
> +  $input.setAttribute("placeholder", placeholder);
통일성을 위해서 template을 변수로 하지말고, 함수로 하는것도 좋은 방법 같은데 어떻게 생각하시나요 ?? 
이 부분에 대해서는 저도 ㅠㅠ 저런 식으로 작성하거나 함수였다면 더 편할 것 같다고 생각했거든요!

2021-07-19 04:04 UTC, hwookim commented on frontend/src/components/Input/index.ts
> +  $input.setAttribute("placeholder", placeholder);
함수로 작성하는 방식도 좋은 것 같습니다!

2021-07-19 04:04 UTC, hwookim commented on frontend/src/components/Input/style.scss
> +@import "@/common/variables.scss";
저는 일단 IDE에서 오류로 잡긴 합니다🤔

2021-07-19 04:06 UTC, hwookim commented on frontend/src/components/Input/index.ts
> +  $input.setAttribute("placeholder", placeholder);
그럼 전체적으로 한번에 수정할 수 있도록 별도 이슈로 작성할까요?

2021-07-19 05:19 UTC, hwookim approved these changes
아마 충돌이 많이 생길 것 같네요..😅
그 부분만 해결해주시면 괜찮은 것 같습니다!

2021-07-19 05:26 UTC, juyoungpark718 commented on frontend/src/components/Input/style.scss
> +@import "@/common/variables.scss";
그러면 해당 부분 고치도록 하겠습니다 !

2021-07-19 05:39 UTC, merged